function M = boundaryFilter(I)
  [height, width] = size(I);
  %disp(height);
  %disp(width);
  M = I;
  for row = 2 : height-1
    for col = 2 : width-1
      minPx = min([I(row,col+1) ...
          I(row-1,col+1) ...
          I(row-1,col) ...
          I(row-1,col-1) ...
          I(row,col-1) ...
          I(row+1,col-1) ...
          I(row+1,col) ...
          I(row+1,col+1) ...
          I(row,col)]);
      maxPx = max([I(row,col+1) ...
          I(row-1,col+1) ...
          I(row-1,col) ...
          I(row-1,col-1) ...
          I(row,col-1) ...
          I(row+1,col-1) ...
          I(row+1,col) ...
          I(row+1,col+1) ...
          I(row,col)]);
      if M(row,col) < minPx
        M(row,col) = minPx;
      else
        if M(row,col) > maxPx
          M(row,col) = maxPx;
        endif
      endif
    endfor
  endfor
end
