function M = medianFilter(I)
  [height, width] = size(I);
  %disp(height);
  %disp(width);
  M = I;
  for row = 2 : height-1
    for col = 2 : width-1
      med = median([I(row,col+1) ...
          I(row-1,col+1) ...
          I(row-1,col) ...
          I(row-1,col-1) ...
          I(row,col-1) ...
          I(row+1,col-1) ...
          I(row+1,col) ...
          I(row+1,col+1) ...
          I(row,col)]);
      M(row,col) = med;
    endfor
  endfor
end

